mysite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = patterns(
    "",
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"", include("submissions.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

submissions/urls.py
from django.conf.urls import patterns, include, url

from views import submission, SubmissionListView, SubmissionUpdateView, ImageCreateView, delete_image
from django.views.decorators.cache import cache_page


urlpatterns = patterns(
    "",
    url(r"^$", cache_page(60*15)(SubmissionListView.as_view()), name='home'),
    url(r"^submit/", submission, name='submit'),
    url(r"^edit/(?P<pk>[0-9]+)/$", SubmissionUpdateView.as_view(), name='submission-edit'),
    url(r"^edit/(?P<pk>[0-9]+)/upload_image/$", ImageCreateView.as_view(), name='jfu-upload'),
    url(r"^edit/(?P<pk>[0-9]+)/delete_image/$", delete_image, name='jfu-delete'),
    url(r"^edit/(?P<pk>[0-9]+)/links/$", delete_image, name='link-inlines'),
)

submissions/models.py
from django.db import models
from django.contrib.auth.models import User
import micawber

class Submission(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    submitted_at = models.DateTimeField(null=True, blank=True)
    accepted_at = models.DateTimeField(null=True, blank=True)
    accepted_by = models.ForeignKey(User, null=True, blank=True, related_name='accepted_submissions')
    message = models.TextField(blank=True, null=True, help_text='If you\'d like, leave a private message to partner and family (not public)')
    name = models.CharField(max_length=200,blank=True, null=True,
            help_text="<b>Name, Location</b> would be ideal")
    email = models.CharField(max_length=200,blank=True, null=True, help_text="Give us a way to contact you (not public)")

    text = models.TextField(blank=True, help_text='A story about how he touched your life, or anything else you want to share. <small>(markdown formatting available)</small>')

    @models.permalink
    def get_absolute_url(self):
        return ('submission-edit', tuple(), {'pk': self.id,},)

    @property
    def current_files(self):
        return [x for x in self.image_set.all() if x.file]

    def __unicode__(self):
        return u'Submission by %s (%s)' % (self.name, (self.text or
            '')[:20],)

class Image(models.Model):
    submission = models.ForeignKey(Submission)
    file = models.ImageField()

class Link(models.Model):
    submission = models.ForeignKey(Submission)
    link = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)

    embed = models.TextField(null=True,blank=True)

    def save(self, *args, **kwargs):
        providers = micawber.bootstrap_basic()
        try:
            self.embed = providers.request(self.link)['html']
        except micawber.ProviderException,e:
            self.embed = None
        super(Link,self).save(*args, **kwargs)

submissions/views.py
import os

from django.conf import settings
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from models import Submission, Image, Link
from django.forms.models import ModelForm, inlineformset_factory
from django.forms.utils import ErrorList
from django import forms
from datetime import datetime
from django.contrib import messages
from extra_views import InlineFormSet
from extra_views.advanced import UpdateWithInlinesView

class LinkInline(InlineFormSet):
    model = Link
    fields=['link','description']

class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        widgets={'message': forms.Textarea(attrs={'rows':2, 'cols':15}),
                 'text': forms.Textarea(attrs={'rows':4, 'cols':15})}
        fields = ['text','message','name','email',]

    def save(self, commit=True):
        x = super(SubmissionForm, self).save(commit=False)
        if 'send' in self.data:
            x.submitted_at = datetime.now()
        if commit:
            x.save()
        return x

    def clean_name(self):
        data = self.cleaned_data
        if 'send' in self.data:
            if not data.get('name', None):
                raise forms.ValidationError('Name needed for submission!')
        return data.get('name', None)

    def clean_text(self):
        data = self.cleaned_data
        if 'send' in self.data:
            if not data.get('text', None) and not self.instance.current_files:
                raise forms.ValidationError('Text or Pictures needed for submission!')
        return data.get('text', None)



class SubmissionListView(ListView):
    queryset = Submission.objects.filter(accepted_at__isnull=False).order_by('-accepted_at')

class SubmissionUpdateView(UpdateWithInlinesView):
    model = Submission
    form_class = SubmissionForm
    inlines = [LinkInline]

    def get_queryset(self):
        base_qs = super(SubmissionUpdateView, self).get_queryset()

        sid = self.request.session.get('submission_id',None)
        if not sid:
            sid = Submission.objects.create().pk
        self.request.session['submission_id'] = sid
        return base_qs.filter(pk=sid, accepted_at__isnull=True)

    def form_valid(self, form):
        if 'send' in self.request.POST:
            self.object = form.save()
            if self.object.name:
                self.object.submitted_at = datetime.now()
            self.object.save()
            if self.object.name and (self.object.text or self.object.current_files):
                messages.success(self.request, 'Thank you. A moderator will publish your submission as soon as possible!')
                return HttpResponseRedirect('/')
            else:
                error = form._errors.setdefault('name', ErrorList())
                error.append('Needed for submission!')
                if not self.object.name and not self.object.current_files:
                    error = form._errors.setdefault('text', ErrorList())
                    error.append('Please upload Images or add Text to submit.')
                return super(SubmissionUpdateView, self).form_invalid(form)


        return super(SubmissionUpdateView, self).form_valid(form)


def submission(request):
    sid = request.session.get('submission_id',None)
    if not sid or Submission.objects.get(pk=sid).submitted_at:
        sid = Submission.objects.create().pk
    request.session['submission_id'] = sid
    s, created = Submission.objects.get_or_create(pk=sid,
        submitted_at__isnull=True)
    return HttpResponseRedirect(s.get_absolute_url())

class ImageCreateView(CreateView):
    model = Image
    fields = ['file']

    def form_valid(self, form):
        form.instance.submission = Submission.objects.get(pk=self.kwargs['pk'], submitted_at__isnull=True)
        self.object = form.save()
        data = {'status': 'success', 'removeLink': reverse('jfu-delete', kwargs={'pk': self.object.pk})}
        response = JsonResponse(data)
        return response

    def form_invalid(self, form):
        return HttpResponse('Not an Image', status=500)

def delete_image(request, pk):
    success = True
    try:
        instance = Image.objects.get( pk = pk )
        if request.session['submission_id']==instance.submission.pk:
            os.unlink( instance.file.path )
            instance.delete()
        else:
            success = False
    except Image.DoesNotExist:
        success = False

    return HttpResponse(  'ok, gone' )


def LinkView(InlineFormSetView):
    model = Submission
    inlines = [LinkInline]

mysite/templates/413.html
File Upload too large, sorry!

mysite/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

mysite/templates/_footer.html
{% load i18n %}

&copy; cc-by-sa Some people; Photo Uploads and Texts by their respective authors.

mysite/templates/_person_header.html
{% load static %}
  <div class="container">
    <div class="well header">
      <h1><a href="/">PAGE TITLE</a></h1>
      <div class="row" style="min-height: 150px;">
        <div class="col-xs-4 text-center col-xs-offset-4">
          <h4>We miss someone</h4>
          <p>add a subtitle</p>
          <img src="{% static 'images/person.png' %}" class="img-responsive"/>
        </div>
      </div>
      <div class="row">
        <p class="text-center">
          <br />
          <a href="{% url 'submit' %}" class="btn btn-primary">Submit Story or Pictures</a>
        </p>
      </div>
    </div>
  </div>

mysite/templates/_scripts.html
<script src='/site_media/static/js/site.js?4b14ff1600032f0b279c'></script>

mysite/templates/_styles.html
<link href='/site_media/static/css/site.css?4b14ff1600032f0b279c' rel='stylesheet' />

mysite/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load i18n %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}

{% block topbar_base %}
    {% include "_person_header.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

mysite/templates/wiki/edit.html
{% extends "site_base.html" %}

{% load bootstrap %}

{% block title %}
    {% if page.pk %}
        Edit {{ page.slug }}
    {% else %}
        Add {{ page.slug }}
    {% endif %}
{% endblock %}

{% block body_class %}wiki-edit{% endblock %}

{% block body %}
    <h1>
        {% if page.pk %}
            Edit {{ page.slug }}
        {% else %}
            Add {{ page.slug }}
        {% endif %}
    </h1>

    <form class="form dropzone" method="POST" action="">
        {% csrf_token %}
        <p>
            To include an image on a card, drag it to this form or <a href="#" class="file-browse">browse for a file</a>.
        </p>
        <input type="file" class="hide fileupload" name="files" data-url="{% url 'wiki_file_upload' %}" multiple>
        <div class="progress progress-striped hide">
            <div class="progress-bar" role="progressbar" style="width: 0%;"></div>
        </div>
        {{ form|bootstrap }}
        <div class="pull-right">
            <a href="{{ page.get_absolute_url }}" class="btn btn-default">Cancel</a>
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

mysite/templates/wiki/page.html
{% extends "site_base.html" %}

{% block body %}

    {% if can_edit %}
        <a class="pull-right btn btn-xs btn-primary" href="{{ revision.page.get_edit_url }}">Edit</a>
    {% endif %}

    <div class="page">
        {{ revision.content_html|safe }}
    </div>
{% endblock %}

submissions/templates/submissions/submission_form.html
{% extends "site_base.html" %}

{% load staticfiles %}
{% load bootstrap %}

{% block extra_head %}
  <link rel="stylesheet" href="{% static 'css/dropzone.css' %}" />
{% endblock %}


{% block body %}

{% include "_header.html" %}

<script src="{% static 'js/dropzone.js' %}"></script>
<script>
Dropzone.options.dropzoneFiles = {};
Dropzone.options.dropzoneFiles['maxFilesize'] = 2;
Dropzone.options.dropzoneFiles['acceptedFiles'] = 'image/*';
Dropzone.options.dropzoneFiles['dictDefaultMessage'] = 'Drag & Drop or Click to add Images';
Dropzone.options.dropzoneFiles['dictRemoveFile'] = 'X';
Dropzone.options.dropzoneFiles['addRemoveLinks'] = true;
Dropzone.options.dropzoneFiles['addedfile'] = function(file, div) {
  console.log(this,file);
  this.defaultOptions.addedfile.call(this, file, div);
  if(file.status==Dropzone.SUCCESS) {
    this.defaultOptions.success.call(this, file, div);
  }
};
Dropzone.options.dropzoneFiles['removedfile'] = function(file) {
  $.post(file.removeLink, {});
  file.previewElement.parentNode.removeChild(file.previewElement);
  console.log(file);
  return true;
};
Dropzone.options.dropzoneFiles['success'] = function(file, response) {
  file.removeLink = response.removeLink;
};
Dropzone.options.dropzoneFiles['init'] = function() {
  var file = null;
  {% for file in form.instance.current_files %}
    file = {
      filename: "{{ file.file.name|escapejs }}",
      name: "{{ file.file.name|escapejs }}",
      size: "{{ file.file.size}}",
      type: "image/jpeg",
      removeLink: "{% url 'jfu-delete' pk=file.pk %}",
      status: Dropzone.SUCCESS,
      upload: {progress: 100, bytesSent: {{file.file.size}}, total: {{file.file.size}}},
      accepted: true
    };
    this.options.addedfile.call(this, file);
    this.options.thumbnail.call(this,file, '{{file.file.url}}');
    this.options.complete.call(this,file, file.upload.progress, file.upload.bytesSent);
    this.files.push(file);
  {% endfor %}
}
</script>

<div class="thecontent well">
  <h2>Your Submission</h2>
  {% if form.instance.submitted_at %}
    <div class="alert alert-info">
      You have submitted this! The moderation team will publish it shortly.<br />
      You can still change this until you navigate away from this page.
    </div>
  {% else %}
    <p>Upload files, create Text, feel free to save before submitting.</p>
    <p>Entries are moderated, so it will be a while before they show up on the site</p>
  {% endif %}
  <hr />
  <div class="row">
    <div class="col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
      <label>Pictures <small style="font-weight: normal">File size: up to 2MB</small></label>
      <form action="{% url 'jfu-upload' pk=form.instance.pk %}" method="POST" class="dropzone" id="dropzone-files">
        {% csrf_token %}
        <div class="fallback">
          <input name="file" type="file" multiple />
        </div>
      </form>
    </div>
  </div>
  <form method="POST">
    <div class="row">
      <div class="col-md-6" class="form-horizontal">
        {{form|bootstrap_horizontal}}
        {% csrf_token %}
      </div>
      <div class="col-xs-8 col-xs-offset-2 col-md-5 col-md-offset-1">
        <label>Links &amp; Videos</label>
        {% for links_formset in inlines %}
          {{links_formset.management_form}}
          {% for inline in links_formset %}
            <div class="form-inline">
              {{inline|bootstrap}}
            </div>
          {% endfor %}
        {% endfor %}
        <p class="small"><br />Vimeo and Youtube links will be embedded, like pictures</p>
      </div>
    </div>
    <div class="row">
      <div class="text-center">
        <span>
          <input type="submit" class="btn btn-primary" name="save" value="Entwurf speichern"/>
          <input type="submit" class="btn btn-success" name="send" value="Abschicken (final)"/>
        </span>
      </div>
    </div>
  </form>
</div>
{% endblock %}

submissions/templates/submissions/submission_list.html
{% extends "site_base.html" %}

{% load md2 %}

{% block body %}
    {% for submission in object_list %}
    {% if not forloop.first %}
    <p class="text-center divider"><span class="glyphicon glyphicon glyphicon-option-horizontal" aria-hidden="true"></span></p>
    {% endif %}
    <div class="submission">
      <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 well">
          {% if submission.current_files %}
            <div class="carousel slide" data-ride="carousel" id="carousel-{{submission.pk}}">
              <div class="carousel-inner" role="listbox">
                {% for image in submission.current_files %}
                <div class="item {% if forloop.first %}active{%endif %}"><img src="{{ image.file.url }}"/> </div>
                {% endfor %}
              </div>
              {% if submission.current_files|length > 1 %}
              <a class="left carousel-control" href="#carousel-{{submission.pk}}" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-{{submission.pk}}" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
              {% endif %}
            </div>
          {% endif %}
          {% if submission.link_set.all %}
          {% for link in submission.link_set.all %}
            <div class="row-flexible">
              <div class="col-xs-12">
                <div class="panel panel-default">
                  {% if link.embed %}
                    <div class="panel-content embed-responsive embed-responsive-16by9">
                      {{link.embed|safe}}
                    </div>
                    <div class="panel-footer">
                      {{link.description}}
                    </div>
                  {% else %}
                    <div class="panel-footer">
                      <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
                      <a href="{{link.link}}" target="_blank">{{link.description}}</a>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
          {% endfor %}
          {% endif %}
          <div class="text">
            {% if submission.text %}{{ submission.text | markdown }}{% endif %}
            <p class="by">— {{submission.name}}</p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
{% endblock %}